#!/bin/bash

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export MOZ_NO_REMOTE=1
export XSESSION="herbstluftwm"
exec "herbstluftwm"

/usr/bin/xset m 4 0
/usr/bin/xset m 4 0
/usr/bin/xset m 4 0
/usr/bin/xset -b
/usr/bin/redshift -x
/usr/bin/redshift -O 3500K
