syntax on
colorscheme solarized
set nocursorline

set nocompatible
set term=screen-256color
set nowrap
set autoindent
set copyindent
set ignorecase
set smartcase
set showtabline=2
set textwidth=0
set tw=0
set history=100
set undolevels=100
set incsearch
set viminfo=""
set number
set tabpagemax=100
filetype indent on
set directory=~/.swp//

map <F14> :setlocal spell spelllang=en_us <cr>
map <F15> :setlocal spell spelllang= <cr>
map <F17> :set nonumber <cr>
map <F18> :set wrap <cr>
map <F19> :set textwidth=0 <cr>

set autoindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set hlsearch
set nocursorline
