#!/bin/bash

# INITIALIZE
feh --bg-scale /hdd/jkl/config/t440s/bash/_mosaic.png
xbacklight =20 -steps 1
amixer -D pulse -- sset Master unmute 20%
amixer -D pulse -- sset Capture unmute 100%

function hc() 
{
	cmds="$cmds , $@"
}
cmds=''
hc emit_hook reload

# SETTINGS
hc set frame_bg_transparent 100
hc set frame_border_width 0
hc set window_border_width 0
hc set window_border_inner_width 0
hc set frame_gap 0
hc set frame_padding 0
hc set window_gap 0
hc set snap_distance 24
hc set snap_gap 0
hc set always_show_frame 09fbc00
hc set default_frame_layout 2
hc set focus_follows_mouse 1
hc set raise_on_click 1
hc set raise_on_focus 0

# BASIC SETTINGS
hc rename default F1 || true
hc add F2
hc add F3
hc set_layout max

# RESET KEY BINDINGS
hc keyunbind --all
m=Mod4

# KEYS: WINDOW MANAGER MANAGEMENT
hc keybind $m-Control-Shift-q quit
hc keybind $m-Control-Delete reload
hc keybind $m-Alt-Escape reload
hc keybind $m-Escape close
hc keybind $m-Control-d toggle focus_follows_mouse
hc keybind $m-Control-r spawn /home/jason/jkl/bin/t440s/hcrules
hc keybind $m-y spawn /usr/bin/mpv /home/jason/youtube/blank.jpg

# KEYS: WINDOW MANAGER HACKS
hc keybind $m-Control-a spawn xdotool mousemove 9 90 click --repeat 2 --delay 300 1
hc keybind $m-Control-x spawn xdotool mousemove 1366 768
hc keybind $m-b spawn xdotool mousemove 5000 5000 
hc keybind $m-Alt-k spawn xdotool mousemove_relative -- 0 -10
hc keybind $m-Alt-l spawn xdotool mousemove_relative -- 10 0
hc keybind $m-Alt-j spawn xdotool mousemove_relative -- 0 10
hc keybind $m-Alt-h spawn xdotool mousemove_relative -- -10 0
hc keybind $m-Alt-semicolon spawn xdotool click 1
hc keybind $m-q spawn xterm -e 'herbstclient remove && herbstclient remove && herbstclient remove && herbstclient remove && herbstclient remove && herbstclient remove && herbstclient remove && herbstclient floating off && herbstclient set_layout max'

# KEYS: APPLICATION
hc keybind $m-c spawn urxvt -e screen
hc keybind $m-v spawn /home/jason/jkl/bin/t440s/vimperator
hc keybind $m-Shift-v spawn firefox-bin -P
hc keybind $m-Alt-v spawn google-chrome-stable --force-device-scale-factor=1
hc keybind $m-m spawn /home/jason/jkl/bin/t440s/jlpdf z
#hc keybind $m-m spawn /home/jason/jkl/bin/t400s/jlpdf m
hc keybind $m-i spawn /home/jason/jkl/repo/sxiv-jkl/scripts/jlsxiv
hc keybind $m-Control-Shift-p spawn /home/jason/jkl/bin/t440s/jlscreenshot
hc keybind $m-Shift-p spawn /home/jason/jkl/bin/t440s/jlscreenshot

# KEYS: SPECIAL INFORMATION
hc keybind $m-Shift-1 spawn /home/jason/jkl/bin/t440s/bindmenu
hc keybind $m-Shift-semicolon spawn /home/jason/jkl/bin/t440s/hcdmenu
hc keybind $m-a spawn /home/jason/jkl/bin/t440s/statusbar hcinfo
hc keybind $m-w spawn /home/jason/jkl/bin/t440s/statusbar hcwin

# KEYS: MANAGE INDEXES
hc keybind $m-Tab use_index +1
hc keybind $m-Shift-Tab use_index -1
hc keybind $m-Right use_index +1
hc keybind $m-Left use_index -1
hc keybind $m-Shift-a move_index -1
hc keybind $m-Shift-d move_index +1
hc keybind $m-Shift-F1 use_index F1
hc keybind $m-Shift-F2 use_index F2
hc keybind $m-Shift-F3 use_index F3

# KEYS: CHOOSE LAYOUT GRID
hc keybind $m-z cycle_layout
hc keybind $m-Shift-z set_layout max
hc keybind $m-Control-z set_layout grid

# KEYS: ADJUST LAYOUT GRID
hc keybind $m-s split vertical 0.5
hc keybind $m-Shift-s split horizontal 0.5
hc keybind $m-r remove
#hc keybind $m-d cycle_all +1
#hc keybind $m-Shift-n cycle_all +1
#hc keybind $m-Shift-p cycle_all -1
hc keybind $m-x cycle
hc keybind $m-n cycle +1
hc keybind $m-p cycle -1
hc keybind $m-h focus left
hc keybind $m-j focus down
hc keybind $m-k focus up
hc keybind $m-l focus right
hc keybind $m-Control-h shift left
hc keybind $m-Control-j shift down
hc keybind $m-Control-k shift up
hc keybind $m-Control-l shift right

# KEYS: RESIZE GRID
hc keybind $m-Shift-h resize left +0.01
hc keybind $m-Shift-j resize down +0.01
hc keybind $m-Shift-k resize up +0.01
hc keybind $m-Shift-l resize right +0.01

# KEYS: CHOOSE MISCELLANEOUS LAYOUT TYPES
hc keybind $m-F1 floating toggle
hc keybind $m-F2 fullscreen toggle
hc keybind $m-F3 pseudotile toggle
hc keybind $m-f floating toggle
hc keybind $m-Shift-f fullscreen toggle
hc keybind $m-Control-f pseudotile toggle
hc keybind $m-Shift-x fullscreen toggle

## KEYS: VOLUME CONTROLS
hc keybind $m-equal spawn amixer -D pulse -- set Master 2%+
hc keybind $m-minus spawn amixer -D pulse -- set Master 2%-
hc keybind $m-grave spawn amixer -D pulse -- sset Master mute
hc keybind $m-1 spawn amixer -D pulse -- sset Master unmute 100%
hc keybind $m-2 spawn amixer -D pulse -- sset Master unmute 90%
hc keybind $m-3 spawn amixer -D pulse -- sset Master unmute 80%
hc keybind $m-4 spawn amixer -D pulse -- sset Master unmute 70%
hc keybind $m-5 spawn amixer -D pulse -- sset Master unmute 60%
hc keybind $m-6 spawn amixer -D pulse -- sset Master unmute 50%
hc keybind $m-7 spawn amixer -D pulse -- sset Master unmute 40%
hc keybind $m-8 spawn amixer -D pulse -- sset Master unmute 30%
hc keybind $m-9 spawn amixer -D pulse -- sset Master unmute 20%
hc keybind $m-0 spawn amixer -D pulse -- sset Master unmute 10%

# KEYS: BACKLIGHT CONTROLS
hc keybind $m-Control-equal spawn xbacklight +2
hc keybind $m-Control-minus spawn xbacklight -2
hc keybind $m-Control-grave spawn xbacklight =0
hc keybind $m-Control-1 spawn xbacklight =100
hc keybind $m-Control-2 spawn xbacklight =90
hc keybind $m-Control-3 spawn xbacklight =80
hc keybind $m-Control-4 spawn xbacklight =70
hc keybind $m-Control-5 spawn xbacklight =60
hc keybind $m-Control-6 spawn xbacklight =50
hc keybind $m-Control-7 spawn xbacklight =40
hc keybind $m-Control-8 spawn xbacklight =30
hc keybind $m-Control-9 spawn xbacklight =20
hc keybind $m-Control-0 spawn xbacklight =10

# KEYS: MOUSE BINDINGS
hc keybind $m-Control-m spawn /usr/bin/xset m 2
hc mouseunbind --all
hc mousebind $m-Button1 move
hc mousebind $m-Button2 resize
hc mousebind $m-Button3 zoom
hc mousebind $m-Control-Button1 zoom
hc mousebind $m-Shift-Button1 resize

# INITIALIZE HERBSTLUFTWM BINDINGS
herbstclient chain $cmds &
wmname LG3D

# INITIAL CLEANUP
rm -Rf /hdd/.trash/* /hdd/.trash/.* /home/jason/.trash/* /home/jason/.trash/.*
rm /home/jason/.serverauth* /home/jason/.bash_history /home/jason/.xaut*

# DISABLE TOUCHPAD TAP/SCROLL WHILE TYPING
killall syndaemon
if [[ -z $(ps -A | grep "syndaemon") ]]; then syndaemon -i 0.5 -t -d; fi

# DISABLE SCREENSAVER/BLANKING
/usr/bin/xset -dpms
/usr/bin/xset s noblank
/usr/bin/xset s off
/usr/bin/xset m 4 0
/usr/bin/xset m 4 0
/usr/bin/xset m 4 0
/usr/bin/setxkbmap -option ctrl:nocaps

# RULES
herbstclient unrule -F
herbstclient rule focus=off pseudotile=off manage=on # normal rules
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' focus=off pseudotile=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=on
herbstclient rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on manage=on
herbstclient rule title='statusbar_info;sleep 5;exit' pseudotile=on manage=off focus=on
herbstclient rule title='statusbar_hcwin;sleep 5;exit' pseudotile=on manage=off focus=on
herbstclient rule class='TkFDialog' pseudotile=off
herbstclient rule class='sxiv' focus=off fullscreen=off
