#!/bin/bash

export MOZ_NO_REMOTE=1
export XSESSION="herbstluftwm"
exec herbstluftwm --locked

#/usr/bin/xset m 4 0
#/usr/bin/xset m 4 0
#/usr/bin/xset m 4 0
/usr/bin/xset -b
/usr/bin/xset s off -dpms
