#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

feh --bg-scale /home/laij/jkl/config/t440s/bash/_mosaic.png

# keybindings
Mod=Mod4   # Use the super key as the main modifier

# SETTINGS
hc set frame_bg_transparent 100
hc set frame_border_width 0
hc set window_border_width 0
hc set window_border_inner_width 0
hc set frame_gap 0
hc set frame_padding 0
hc set window_gap 0
hc set snap_distance 24
hc set snap_gap 0
hc set always_show_frame 09fbc00
hc set default_frame_layout 2
hc set focus_follows_mouse 1
hc set raise_on_click 1
hc set raise_on_focus 0
hc pad 0 0 0 0 0
#hc set_layout max # gives an error when ran in autostart

m=Mod4
hc keybind $m-c spawn urxvt -e screen
hc emit_hook reload
hc keybind $m-Control-Shift-q quit
hc keybind $m-Control-Delete reload
hc keybind $m-Alt-Escape reload
hc keybind $m-Escape close
hc keybind $m-Control-d toggle focus_follows_mouse
hc keybind $m-q spawn xterm -e 'herbstclient remove && herbstclient remove && herbstclient remove && herbstclient remove && herbstclient remove && herbstclient remove && herbstclient remove && herbstclient floating off && herbstclient set_layout max'

hc keybind $m-c spawn urxvt -e screen

hc keybind $m-Tab use_index +1
hc keybind $m-Shift-Tab use_index -1
hc keybind $m-Right use_index +1
hc keybind $m-Left use_index -1
hc keybind $m-Shift-a move_index -1
hc keybind $m-Shift-d move_index +1
hc keybind $m-Shift-F1 use_index F1
hc keybind $m-Shift-F2 use_index F2
hc keybind $m-Shift-F3 use_index F3

# KEYS: CHOOSE LAYOUT GRID
hc keybind $m-z cycle_layout
hc keybind $m-Shift-z set_layout max
hc keybind $m-Control-z set_layout grid

## KEYS: ADJUST LAYOUT GRID
hc keybind $m-s split vertical 0.5
hc keybind $m-Shift-s split horizontal 0.5
hc keybind $m-r remove
#hc keybind $m-d cycle_all +1
#hc keybind $m-Shift-n cycle_all +1
#hc keybind $m-Shift-p cycle_all -1
hc keybind $m-x cycle
hc keybind $m-n cycle +1
hc keybind $m-p cycle -1
hc keybind $m-h focus left
hc keybind $m-j focus down
hc keybind $m-k focus up
hc keybind $m-l focus right
hc keybind $m-Control-h shift left
hc keybind $m-Control-j shift down
hc keybind $m-Control-k shift up
hc keybind $m-Control-l shift right

# KEYS: RESIZE GRID
hc keybind $m-Shift-h resize left +0.01
hc keybind $m-Shift-j resize down +0.01
hc keybind $m-Shift-k resize up +0.01
hc keybind $m-Shift-l resize right +0.01

# KEYS: CHOOSE MISCELLANEOUS LAYOUT TYPES
hc keybind $m-F1 floating toggle
hc keybind $m-F2 fullscreen toggle
hc keybind $m-F3 pseudotile toggle
hc keybind $m-f floating toggle
hc keybind $m-Shift-f fullscreen toggle
hc keybind $m-Control-f pseudotile toggle
hc keybind $m-Shift-x fullscreen toggle

# KEYS: MOUSE BINDINGS
hc mouseunbind --all
hc mousebind $m-Button1 move
hc mousebind $m-Button2 resize
hc mousebind $m-Button3 zoom
hc mousebind $m-Control-Button1 zoom
hc mousebind $m-Shift-Button1 resize

# KEYS: VBOX SPECIFIC
hc keybind $m-Shift-F1 use_index F1
hc keybind $m-F12 spawn /home/laij/jkl/bin/vbox/1920x1020.sh
hc keybind $m-F11 spawn /home/laij/jkl/bin/vbox/1600x900.sh
hc keybind $m-F10 spawn /home/laij/jkl/bin/vbox/1280x720.sh
hc keybind $m-F9 spawn /home/laij/jkl/bin/vbox/1024x768.sh
hc keybind $m-F8 spawn /home/laij/jkl/bin/vbox/800x600.sh
hc keybind $m-F7 spawn /home/laij/jkl/bin/vbox/640x480.sh

## DISABLE SCREENSAVER/BLANKING
#/usr/bin/xset -dpms
#/usr/bin/xset s noblank
#/usr/bin/xset s off
#/usr/bin/xset m 4 0
#/usr/bin/xset m 4 0
#/usr/bin/xset m 4 0
#/usr/bin/setxkbmap -option ctrl:nocaps

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

