syntax on
colorscheme solarized

set nocompatible
set term=screen-256color
set nowrap
set autoindent
set copyindent
set ignorecase
set smartcase
set showtabline=2
set textwidth=0
set history=1000
set undolevels=1000
set incsearch
set viminfo=""
set number
set ruler
set tabpagemax=100
filetype indent on
set directory=~/.swp//

"map <F14> :setlocal spell spelllang=en_us <cr>
"map <F15> :setlocal spell spelllang= <cr>
"map <F17> :set nonumber <cr>
"map <F18> :set wrap <cr>
"map <F19> :set textwidth=0 <cr>

set autoindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set hlsearch
set expandtab
set nocursorline

autocmd BufRead,BufNewFile *.prn set noexpandtab
autocmd FileType cpp set tabstop=2 | set softtabstop=2 | set shiftwidth=2 | set textwidth=120 | set noexpandtab
autocmd FileType python set tabstop=4 |set softtabstop=4 | set shiftwidth=4 | set expandtab
